In [2]:
import pandas as pd

In [43]:
const = pd.read_json(r"C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\PI01_DATA03\Datasets\constructors.json",lines=True)
const.head()
const.to_csv('const.csv')

In [51]:
const

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso
...,...,...,...,...,...
206,209,manor,Manor Marussia,British,http://en.wikipedia.org/wiki/Manor_Motorsport
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
208,211,racing_point,Racing Point,British,http://en.wikipedia.org/wiki/Racing_Point_F1_Team
209,213,alphatauri,AlphaTauri,Italian,http://en.wikipedia.org/wiki/Scuderia_AlphaTauri
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team

In [65]:
drivers = pd.read_json(r"C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\PI01_DATA03\Datasets\drivers.json",lines=True)
drivers.head()
#drivers.to_csv('drivers.csv')

,driverId,driverRef,number,code,name,dob,nationality,url
0,1,hamilton,44,HAM,"{'forename': 'Lewis', 'surname': 'Hamilton'}",1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,"{'forename': 'Nick', 'surname': 'Heidfeld'}",1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,"{'forename': 'Nico', 'surname': 'Rosberg'}",1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,"{'forename': 'Fernando', 'surname': 'Alonso'}",1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,"{'forename': 'Heikki', 'surname': 'Kovalainen'}",1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [66]:
drivers=pd.read_csv(r"C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\drivers.csv") 
drivers_filter=drivers.loc[:,["driverId","driverRef","code","nationality"]]  
drivers_filter.to_csv('driversNorm.csv')
driversNorm = pd.read_csv(r'C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\driversNorm.csv')
driversNorm

     Unnamed: 0  driverId          driverRef code nationality
0             0         1           hamilton  HAM     British
1             1         2           heidfeld  HEI      German
2             2         3            rosberg  ROS      German
3             3         4             alonso  ALO     Spanish
4             4         5         kovalainen  KOV     Finnish
..          ...       ...                ...  ...         ...
848         848       850  pietro_fittipaldi  FIT   Brazilian
849         849       851             aitken  AIT     British
850         850       852            tsunoda  TSU    Japanese
851         851       853            mazepin  MAZ     Russian
852         852       854    mick_schumacher  SCH      German

[853 rows x 5 columns]

In [45]:
results = pd.read_json(r"C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\PI01_DATA03\Datasets\results.json",lines=True)
results.head()
results.to_csv('results_salida.csv')

In [46]:
results2=pd.read_csv(r"C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\results_salida.csv") 
results_filter=results2.loc[:,["driverId","constructorId","raceId","positionOrder","points"]]  
results_filter.to_csv('results_filtrados.csv')
results_filtrados = pd.read_csv(r'C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\results_filtrados.csv')

In [47]:
results_filtrados.head()

   Unnamed: 0  driverId  constructorId  raceId  positionOrder  points
0           0         1              1      18              1    10.0
1           1         2              2      18              2     8.0
2           2         3              3      18              3     6.0
3           3         4              4      18              4     5.0
4           4         5              1      18              5     4.0

In [57]:
circuits = pd.read_csv(r'C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\PI01_DATA03\Datasets\circuits.csv')
circuits.head(20)
#circuits.drop(['url'], axis=1, inplace=True)
#circuits.to_csv('circuitsNorm.csv')

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.968000,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.738000,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.510600,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,MontmelÃ³,Spain,41.57000,2.261110,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.405000,130,http://en.wikipedia.org/wiki/Istanbul_Park
5,6,monaco,Circuit de Monaco,Monte-Carlo,Monaco,43.73470,7.420560,7,http://en.wikipedia.org/wiki/Circuit_de_Monaco
6,7,villeneuve,Circuit Gilles Villeneuve,Montreal,Canada,45.50000,-73.522800,13,http://en.wikipedia.org/wiki/Circuit_Gilles_Vi...
7,8,magny_cours,Circuit de Nevers Magny-Cours,Magny Cours,France,46.86420,3.163610,228,http://en.wikipedia.org/wiki/Circuit_de_Nevers...
8,9,silverstone,Silverstone Circuit,Silverstone,UK,52.07860,-1.016940,153,http://en.wikipedia.org/wiki/Silverstone_Circuit
9,10,hockenheimring,Hockenheimring,Hockenheim,Germany,49.32780,8.565830,103,http://en.wikipedia.org/wiki/Hockenheimring
10,11,hungaroring,Hungaroring,Budapest,Hungary,47.57890,19.248600,264,http://en.wikipedia.org/wiki/Hungaroring
11,12,valencia,Valencia Street Circuit,Valencia,Spain,39.45890,-0.331667,4,http://en.wikipedia.org/wiki/Valencia_Street_C...
12,13,spa,Circuit de Spa-Francorchamps,Spa,Belgium,50.43720,5.971390,401,http://en.wikipedia.org/wiki/Circuit_de_Spa-Fr...
13,14,monza,Autodromo Nazionale di Monza,Monza,Italy,45.61560,9.281110,162,http://en.wikipedia.org/wiki/Autodromo_Naziona...
14,15,marina_bay,Marina Bay Street Circuit,Marina Bay,Singapore,1.29140,103.864000,18,http://en.wikipedia.org/wiki/Marina_Bay_Street...
15,16,fuji,Fuji Speedway,Oyama,Japan,35.37170,138.927000,583,http://en.wikipedia.org/wiki/Fuji_Speedway
16,17,shanghai,Shanghai International Circuit,Shanghai,China,31.33890,121.220000,5,http://en.wikipedia.org/wiki/Shanghai_Internat...
17,18,interlagos,AutÃ³dromo JosÃ© Carlos Pace,SÃ£o Paulo,Brazil,-23.70360,-46.699700,785,http://en.wikipedia.org/wiki/Aut%C3%B3dromo_Jo...
18,19,indianapolis,Indianapolis Motor Speedway,Indianapolis,USA,39.79500,-86.234700,223,http://en.wikipedia.org/wiki/Indianapolis_Moto...
19,20,nurburgring,NÃ¼rburgring,NÃ¼rburg,Germany,50.33560,6.947500,578,http://en.wikipedia.org/wiki/N%C3%BCrburgring

In [55]:
circuits.head()

,circuitId,circuitRef,name,location,country,lat,lng,alt
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7
3,4,catalunya,Circuit de Barcelona-Catalunya,MontmelÃ³,Spain,41.57000,2.26111,109
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130

In [63]:
circuits=pd.read_csv(r"C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\PI01_DATA03\Datasets\circuits.csv") 
circuits_filter=circuits.loc[:,["circuitId","name","location","country"]]  
circuits_filter.to_csv('circuitsNorm.csv')
circuitsNorm = pd.read_csv(r'C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\circuitsNorm.csv')
circuitsNorm

,Unnamed: 0,circuitId,name,location,country
0,0,1,Albert Park Grand Prix Circuit,Melbourne,Australia
1,1,2,Sepang International Circuit,Kuala Lumpur,Malaysia
2,2,3,Bahrain International Circuit,Sakhir,Bahrain
3,3,4,Circuit de Barcelona-Catalunya,MontmelÃ³,Spain
4,4,5,Istanbul Park,Istanbul,Turkey
...,...,...,...,...,...
72,72,73,Baku City Circuit,Baku,Azerbaijan
73,73,74,Hanoi Street Circuit,Hanoi,Vietnam
74,74,75,AutÃ³dromo Internacional do Algarve,PortimÃ£o,Portugal
75,75,76,Autodromo Internazionale del Mugello,Mugello,Italy
76,76,77,Jeddah Street Circuit,Jeddah,Saudi Arabia

In [3]:
races = pd.read_csv(r'C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\PI01_DATA03\Datasets\races.csv')
races.head(20)

,raceId,year,round,circuitId,name,date,time,url
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...
5,6,2009,6,6,Monaco Grand Prix,2009-05-24,12:00:00,http://en.wikipedia.org/wiki/2009_Monaco_Grand...
6,7,2009,7,5,Turkish Grand Prix,2009-06-07,12:00:00,http://en.wikipedia.org/wiki/2009_Turkish_Gran...
7,8,2009,8,9,British Grand Prix,2009-06-21,12:00:00,http://en.wikipedia.org/wiki/2009_British_Gran...
8,9,2009,9,20,German Grand Prix,2009-07-12,12:00:00,http://en.wikipedia.org/wiki/2009_German_Grand...
9,10,2009,10,11,Hungarian Grand Prix,2009-07-26,12:00:00,http://en.wikipedia.org/wiki/2009_Hungarian_Gr...
10,11,2009,11,12,European Grand Prix,2009-08-23,12:00:00,http://en.wikipedia.org/wiki/2009_European_Gra...
11,12,2009,12,13,Belgian Grand Prix,2009-08-30,12:00:00,http://en.wikipedia.org/wiki/2009_Belgian_Gran...
12,13,2009,13,14,Italian Grand Prix,2009-09-13,12:00:00,http://en.wikipedia.org/wiki/2009_Italian_Gran...
13,14,2009,14,15,Singapore Grand Prix,2009-09-27,12:00:00,http://en.wikipedia.org/wiki/2009_Singapore_Gr...
14,15,2009,15,22,Japanese Grand Prix,2009-10-04,05:00:00,http://en.wikipedia.org/wiki/2009_Japanese_Gra...
15,16,2009,16,18,Brazilian Grand Prix,2009-10-18,16:00:00,http://en.wikipedia.org/wiki/2009_Brazilian_Gr...
16,17,2009,17,24,Abu Dhabi Grand Prix,2009-11-01,11:00:00,http://en.wikipedia.org/wiki/2009_Abu_Dhabi_Gr...
17,18,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...
18,19,2008,2,2,Malaysian Grand Prix,2008-03-23,07:00:00,http://en.wikipedia.org/wiki/2008_Malaysian_Gr...
19,20,2008,3,3,Bahrain Grand Prix,2008-04-06,11:30:00,http://en.wikipedia.org/wiki/2008_Bahrain_Gran...

In [5]:
races=pd.read_csv(r"C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\PI01_DATA03\Datasets\races.csv") 
races_filter=races.loc[:,["raceId","year","round","circuitId", 'name']]  
races_filter.to_csv('raceNorm.csv')
racesNorm = pd.read_csv(r'C:\Users\Santi\OneDrive\Escritorio\HENRY TPS\tp1\PI01_DATA03\raceNorm.csv')
racesNorm

      Unnamed: 0  raceId  year  round  circuitId                      name
0              0       1  2009      1          1     Australian Grand Prix
1              1       2  2009      2          2      Malaysian Grand Prix
2              2       3  2009      3         17        Chinese Grand Prix
3              3       4  2009      4          3        Bahrain Grand Prix
4              4       5  2009      5          4        Spanish Grand Prix
...          ...     ...   ...    ...        ...                       ...
1053        1053    1069  2021     18         69  United States Grand Prix
1054        1054    1070  2021     19         32    Mexico City Grand Prix
1055        1055    1071  2021     20         18      Brazilian Grand Prix
1056        1056    1072  2021     22         77  Saudi Arabian Grand Prix
1057        1057    1073  2021     23         24      Abu Dhabi Grand Prix

[1058 rows x 6 columns]